language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jbhatta/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jbhatta/react-test npm run test

after_success:
  - docker build -t jbhatta/multi-client ./client
  - docker build -t jbhatta/multi-nginx ./nginx
  - docker build -t jbhatta/multi-server ./server
  - docker build -t jbhatta/multi-worker ./worker
  # Login to the docker CLI
  - echo "DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jbhatta/multi-client
  - docker push jbhatta/multi-nginx
  - docker push jbhatta/multi-server
  - docker push jbhatta/multi-worker
